# -*- coding: utf-8 -*-
"""Task-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQtlgaerFRZ3ilvB9DEodJjrtFctxUSJ
"""

# ==============================
# Problem 1: Unique Words in a Sentence
# ==============================

sentence = input("Enter sentence: ")

words = sentence.split()
unique_words = set(words)

print("Unique words count:", len(unique_words))
print("Unique words:", unique_words)

# ==============================
# Problem 2: Highest Salary from Employee Data
# ==============================

n = int(input("Enter number of employees: "))

employees = {}

for i in range(n):
    name = input("Enter employee name: ")
    salary = int(input("Enter salary: "))
    employees[name] = salary

highest_employee = ""
highest_salary = 0

for name, salary in employees.items():
    if salary > highest_salary:
        highest_salary = salary
        highest_employee = name

print("Highest Salary:", highest_employee, "-", highest_salary)

# ==============================
# Problem 3: Find Maximum and Minimum Values
# ==============================

numbers = list(map(int, input("Enter numbers separated by space: ").split()))

max_value = numbers[0]
min_value = numbers[0]

for num in numbers:
    if num > max_value:
        max_value = num
    if num < min_value:
        min_value = num

print("List:", numbers)
print("Max:", max_value)
print("Min:", min_value)

# ==============================
# Problem 4: Count Products Above 1000
# ==============================

prices = list(map(int, input("Enter product prices separated by space: ").split()))

count = 0

for price in prices:
    if price > 1000:
        count += 1

print("Products above 1000:", count)

# ==============================
# Problem 5: Calculate Attendance Percentage
# ==============================

attendance = input("Enter attendance (P/A) separated by space: ").split()

present_count = 0

for status in attendance:
    if status.upper() == "P":
        present_count += 1

percentage = (present_count / len(attendance)) * 100

print("Attendance Percentage:", percentage)

# ==============================
# Problem 6: Remove Duplicate Phone Numbers
# ==============================

phone_numbers = list(map(int, input("Enter phone numbers separated by space: ").split()))

unique_numbers = set(phone_numbers)

print("Unique phone numbers:", unique_numbers)

# ==============================
# Problem 7: Count Character Frequency
# ==============================

text = input("Enter a string: ")

char_count = {}

for char in text:
    if char in char_count:
        char_count[char] += 1
    else:
        char_count[char] = 1

print("Character Frequency:", char_count)

# ==============================
# Problem 8: Convert List to Tuple
# ==============================

numbers = list(map(int, input("Enter numbers separated by space: ").split()))

my_tuple = tuple(numbers)

print("Tuple:", my_tuple)

# ==============================
# Problem 9: Check if a Key Exists in a Dictionary
# ==============================

n = int(input("Enter number of employees: "))

employees = {}

for i in range(n):
    name = input("Enter employee name: ")
    salary = int(input("Enter salary: "))
    employees[name] = salary

key = input("Enter employee name to check: ")

if key in employees:
    print("Employee exists")
else:
    print("Employee does not exist")

# ==============================
# Problem 10: Calculate Average Marks
# ==============================

marks = list(map(int, input("Enter marks separated by space: ").split()))

total = 0

for mark in marks:
    total += mark

average = total / len(marks)

print("Average Marks:", average)